### ISSUE TITLE
Add UTF-8 Support in Registry Queries

### ISSUE THREAD

**Issue by hegotit** [YesWeDont/winreg2#1]
I've been using `winreg2` for registry operations and encountered issues with non-ASCII characters due to `reg.exe`'s reliance on the current code page. This leads to problems when dealing with keys or values containing characters from languages other than English, especially on systems where changing the global code page isn't an option.

It would be very helpful to have a way to ensure winreg2 can directly handle UTF-8 encoded data, perhaps by temporarily setting a new code page adapted to UTF-8 to handle reg.exe output in UTF-8 format.

**Comment by YesWeDont** [comment]
I've tried to replicate the issue with registry keys/values that are in non-Latin scripts, but (at least on my computer) everything seems to be working just fine, even before I tried implementing a fix changing the code page via `chcp 65001`. Could you give an example of a registry read/write in which the module fails?

**Comment by hegotit** [comment]
> I've tried to replicate the issue with registry keys/values that are in non-Latin scripts, but (at least on my computer) everything seems to be working just fine, even before I tried implementing a fix changing the code page via `chcp 65001`. Could you give an example of a registry read/write in which the module fails?

I apologize for not being clear earlier. My issue concerns non-ASCII characters becoming garbled after retrieval, rather than exceptions thrown during code execution. I suggested adding an option to directly retrieve data in UTF-8 format, eliminating the need for further character set conversions.

Here's an example:
```
import { Hive, Registry } from 'winreg2';

const queryRegistry = async (hive: Hive, reg: string, key: string) => {
  const regKey = new Registry({
    hive: hive,
    key: `${reg}`,
  });

  try {
    const items = await regKey.values();
    const item = items.find((item) => item.name === key);
    return item?.value;
  } catch (err) {
    console.error('Error querying the registry:', err);
    throw err;
  }
};

const test = async (): Promise<string | undefined> => {
  try {
    return await queryRegistry(
      Hive.HKCU,
      '\\Software\\Microsoft\\InputMethod\\Settings\\CHS',
      'UserDefinedDoublePinyinScheme0'
    );
  } catch {
    return undefined;
  }
};

const result: string | undefined = await test();
if (result) {
  console.log(result);
}
```
I expected `小鹤双拼*2*^*iuvdjhcwfg^xmlnpbksqszxkrltvyovt`, but in WebStorm on the Windows 11 Simplified Chinese version, I received:

![image](https://github.com/YesWeDont/winreg2/assets/153287866/974d348c-4fa7-466c-8d04-48209b6480cf)

**Comment by YesWeDont** [comment]
The result that I got on my computer was different (but the tests did fail when I ran the tests with your sample string). I've implemented a fix and with `chcp 65001` and the problem seems to be resolved - try updating the package and see if the problem persists.

**Comment by hegotit** [comment]
> The result that I got on my computer was different (but the tests did fail when I ran the tests with your sample string). I've implemented a fix and with `chcp 65001` and the problem seems to be resolved - try updating the package and see if the problem persists.

Thanks! The problem has been resolved with the updated package.
